CREATE TABLE tasks (
       id BIGINT AUTO_INCREMENT PRIMARY KEY,
       description VARCHAR(255) NOT NULL,
       status ENUM('NEW', 'IN_PROGRESS', 'COMPLETED') NOT NULL,
       last_modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

